language: node_js
sudo: required
dist: trusty
node_js:
  - '6'
before_script:
  - npm install -g bower polymer-cli
  - npm install
  - bower install
branches:
  only:
    - master_staging
script:
 - polymer build

deploy:
  provider: gae
  keyfile: keys/app_engine_key.json
  project: "rumptweets-2c7cc"
  skip_cleanup: true
  default: true
  on: master