language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
before_script:
  - npm install -g bower polymer-cli firebase-tools
script:
  # - xvfb-run npm test
  - cd $TRAVIS_BUILD_DIR/app/front-end-module/
  - bower install
  - polymer build
after_success:
  - echo "Deploying Service";
deploy:
  # deploy master banch to production server
  - provider: script
    script: firebase deploy --token ${FIREBASE_API_TOKEN} --only hosting
    skip_cleanup: true
    on:
      branch: master

  # deploy develop branch to test server
  - provider: gae
    keyfile: keys/app_engine_key.json
    config: app/front-end-module/front-end-module.yaml
    version: develop
    project: "rumptweets-2c7cc"
    skip_cleanup: true
    default: true
    on: 
      branch: develop
  # deploy develop branch to test server
  - provider: gae
    keyfile: keys/app_engine_key.json
    config: app/image-server-module/image-server-module.yaml
    version: develop
    project: "rumptweets-2c7cc"
    skip_cleanup: true
    default: true
    on: 
      branch: develop

  # deploy test branch to test server
  - provider: gae
    keyfile: keys/app_engine_key.json
    config: app/front-end-module/front-end-module.yaml
    version: test
    project: "rumptweets-2c7cc"
    skip_cleanup: true
    default: true
    on: 
      branch: test
  # deploy test branch to test server
  - provider: gae
    keyfile: keys/app_engine_key.json
    config: app/image-server-module/image-server-module.yaml
    version: test
    project: "rumptweets-2c7cc"
    skip_cleanup: true
    default: true
    on: 
      branch: test