language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
branches:
  only:
    - master
before_script:
  - npm install -g bower polymer-cli firebase-tools
  - bower install
script:
  # - xvfb-run npm test
  - polymer build
after_success:
  - firebase deploy --token ${FIREBASE_API_TOKEN}