language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '5'
  - '4'
branches:
  only:
    - master
before_script:
  - npm install -g bower polymer-cli firebase-tools
  - bower install
  - firebase build
script:
  # - xvfb-run npm test
  
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN} --only hosting