language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
before_script:
  - npm install -g bower polymer-cli@next
  - cd $TRAVIS_BUILD_DIR/app/front-end-module/
  - bower install
  - chmod +x $TRAVIS_BUILD_DIR/scripts/bash/deploy.sh
script:
  # - xvfb-run npm test
  - polymer build
after_success:
  - echo "Removing bower compontnts before deploy";
  - rm -r $TRAVIS_BUILD_DIR/app/front-end-module/bower_components
  - echo "Generating deploy script";
  - cd $TRAVIS_BUILD_DIR
  - sh $TRAVIS_BUILD_DIR/scripts/bash/deploy.sh rumptweet-app-module $TRAVIS_BRANCH
deploy:
  - provider: gae
    keyfile: $TRAVIS_BUILD_DIR/keys/app_engine_key.json
    config:  $TRAVIS_BUILD_DIR/app/rumptweet-app-module.yaml
    version: master-${TRAVIS_BUILD_NUMBER}
    project: "rumptweets-2c7cc"
    skip_cleanup: true
    default: true
    on: 
      branch: master
  # How to deploy on the test branch
  - provider: gae
    keyfile: $TRAVIS_BUILD_DIR/keys/app_engine_key.json
    config:  $TRAVIS_BUILD_DIR/app/rumptweet-app-module.yaml
    version: test-${TRAVIS_BUILD_NUMBER}
    project: "rumptweets-2c7cc"
    skip_cleanup: true
    default: true
    on: 
      branch: test
  # How to deploy on the develop branch
  - provider: gae
    keyfile: $TRAVIS_BUILD_DIR/keys/app_engine_key.json
    config:  $TRAVIS_BUILD_DIR/app/rumptweet-app-module.yaml
    version: develop-${TRAVIS_BUILD_NUMBER}
    project: "rumptweets-2c7cc"
    skip_cleanup: true
    default: true
    on: 
      branch: develop
after_deploy:
  - cd $TRAVIS_BUILD_DIR
  - sh gcloud app deploy dispatch.yaml

 