
language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
branches:
  only:
    - master
before_script:
  - npm install -g bower polymer-cli firebase-tools
  - bower install
script:
  # - xvfb-run npm test
  - polymer build
after_success:
  - echo "Deploying Service";
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: scripts/deploy.sh staging
    on:
      branch: test
  # deploy master to production
  - provider: script
    script: scripts/deploy.sh production
    on:
      branch: master